# CircleCI 2.1 configuration file for https://github.com/zxdavb/geniushub-client
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2.1


jobs:

  check_version:
    docker: &docker_config
      - image: cimg/python:3.9.16

    steps:
      - checkout

      - run:
          name: Verify git tag vs. package version
          command: python setup.py verify  # NOTE: $CIRCLE_TAG is not available to su


  check_lint:
    docker: *docker_config

    steps:
      - checkout

      - run:
          command: pip install black isort

      - run:
          name: "Check formatting 1: black"
          command: |
            black --diff --check *client.py
            black --diff --check ramses*

      - run:
          name: "Check formatting 2: isort"
          command: |
            isort --check --diff *client.py
            isort --check --diff ramses*


  run_tests:
    docker: *docker_config

    steps:
      - checkout

      - run: &clear_dev_mode
          name: Clear the DEV_MODE flags, if set
          command: |
            sed -i -e '/__dev_mode__ =/ s/= .*/= False/' ramses_rf/const.py
            sed -i -e '/__dev_mode__ =/ s/= .*/= False/' ramses_rf/protocol/const.py

      - run: &clear_dev_hack
          name: Clear any test/dev, debug flags, if set
          command: |
            sed -i -e '/_DBG.* =/ s/= .*/= False/' ramses_rf/protocol/*.py
            sed -i -e '/DEV_MODE =/ s/= .*/= False/' ramses_rf/protocol/*.py

      - run:
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -e .

      - run:
          command: pytest tests -v


  deploy_package:
    docker: *docker_config

    steps:
      - checkout

      - run: *clear_dev_mode
      - run: *clear_dev_hack

      - run:
          command: pip install twine

      - run:
          command: |
            pip setup.py sdist        # create a source distribution
            pip setup.py bdist_wheel  # create a wheel

      - run:
          name: Upload the package to PyPi
          command: |
            echo -e "[pypi]                                         " >  ~/.pypirc
            echo -e "  username = __token__                         " >> ~/.pypirc
            echo -e "  password = $PYPI_TOKEN                       " >> ~/.pypirc

            twine upload -r pypi dist/*


workflows:
  version: 2

  build-and-deploy:    # will deploy only if the commit has a tag
    jobs:
      - check_version:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - check_lint:
          filters:
            tags:
              only: /.*/

      - run_tests:
          filters:
            tags:
              only: /.*/

      - deploy_package:
          requires:
            - check_version
            - check_lint
            - run_tests
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
